CREATE TABLE jobs (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) UNIQUE NOT NULL,
    skills TEXT[]
);


INSERT INTO jobs (title, skills) VALUES
('mern_developer', ARRAY['React','Node.js','MongoDB','Express','Redux','JWT']),
('java_developer', ARRAY['Java','Spring Boot','Hibernate','MySQL','REST API','JUnit']),
('python_developer', ARRAY['Python','Django','Flask','SQLAlchemy','REST API','Pandas']),
('data_scientist', ARRAY['Python','Pandas','NumPy','Scikit-learn','TensorFlow','NLP']),
('devops_engineer', ARRAY['Docker','Kubernetes','CI/CD','AWS','Terraform','Linux']),
('frontend_developer', ARRAY['HTML','CSS','JavaScript','React','Vue.js','SASS']),
('backend_developer', ARRAY['Node.js','Express','Python','Django','Java','REST API']),
('fullstack_developer', ARRAY['JavaScript','React','Node.js','MongoDB','Express','Redux']),
('aws_engineer', ARRAY['AWS EC2','S3','Lambda','CloudFormation','CloudWatch','IAM']),
('azure_engineer', ARRAY['Azure Functions','Azure DevOps','VMs','Cosmos DB','Active Directory']),
('gcp_engineer', ARRAY['Compute Engine','App Engine','Cloud Functions','BigQuery','Cloud Storage']),
('android_developer', ARRAY['Kotlin','Java','Android SDK','Jetpack','Room','Retrofit']),
('ios_developer', ARRAY['Swift','Objective-C','Xcode','CocoaPods','UIKit','Core Data']),
('machine_learning_engineer', ARRAY['Python','TensorFlow','PyTorch','Scikit-learn','Pandas','NumPy']),
('ai_engineer', ARRAY['Python','TensorFlow','PyTorch','Deep Learning','NLP','Computer Vision']),
('qa_engineer', ARRAY['Selenium','JUnit','Cypress','TestNG','Postman','JIRA']),
('security_engineer', ARRAY['Penetration Testing','Firewalls','Wireshark','Linux','AWS Security','OWASP']),
('data_engineer', ARRAY['Python','SQL','ETL','Airflow','Spark','Hadoop']),
('cloud_architect', ARRAY['AWS','Azure','GCP','Terraform','Kubernetes','Docker']),
('network_engineer', ARRAY['TCP/IP','Routing','Switching','Firewalls','Cisco','Juniper']),
('system_admin', ARRAY['Linux','Windows Server','Shell Scripting','Active Directory','VMware','Networking']),
('blockchain_developer', ARRAY['Solidity','Ethereum','Smart Contracts','Web3.js','Truffle','Ganache']),
('react_native_developer', ARRAY['React Native','JavaScript','Redux','Expo','iOS','Android']),
('flutter_developer', ARRAY['Flutter','Dart','Firebase','REST API','Provider','Bloc']),
('sql_developer', ARRAY['SQL','PL/SQL','MySQL','PostgreSQL','T-SQL','Oracle']),
('big_data_engineer', ARRAY['Hadoop','Spark','Kafka','Python','Hive','HBase']),
('business_analyst', ARRAY['Excel','SQL','Power BI','Tableau','Data Analysis','UML']),
('product_manager', ARRAY['Roadmaps','JIRA','Confluence','Agile','Scrum','Communication']),
('ux_ui_designer', ARRAY['Figma','Sketch','Adobe XD','Wireframing','Prototyping','Usability Testing']),
('game_developer', ARRAY['Unity','C#','Unreal Engine','3D Modeling','Animation','Physics']),
('embedded_systems_engineer', ARRAY['C','C++','Microcontrollers','RTOS','Embedded Linux','Debugging']),
('iot_engineer', ARRAY['Sensors','Arduino','Raspberry Pi','MQTT','Python','C++']),
('ruby_on_rails_developer', ARRAY['Ruby','Rails','PostgreSQL','RSpec','Git','HTML/CSS']),
('php_developer', ARRAY['PHP','Laravel','MySQL','Composer','REST API','JavaScript']),
('angular_developer', ARRAY['Angular','TypeScript','RxJS','NgRx','HTML','CSS']),
('vuejs_developer', ARRAY['Vue.js','Vuex','JavaScript','HTML','CSS','Axios']),
('csharp_developer', ARRAY['C#','ASP.NET','Entity Framework','SQL Server','REST API','MVC']),
('golang_developer', ARRAY['Go','Gin','Gorm','Docker','REST API','Kubernetes']),
('rust_developer', ARRAY['Rust','Actix','Tokio','Serde','Rocket','Cargo']),
('scala_developer', ARRAY['Scala','Akka','Spark','SBT','Functional Programming','Kafka']),
('kotlin_developer', ARRAY['Kotlin','Spring Boot','Android','Coroutines','Ktor','SQL']),
('tensorflow_developer', ARRAY['TensorFlow','Keras','Python','Numpy','Pandas','Deep Learning']),
('pytorch_developer', ARRAY['PyTorch','Python','TensorFlow','NumPy','Pandas','Deep Learning']),
('qa_automation_engineer', ARRAY['Selenium','Cypress','TestNG','JUnit','Python','Java']),
('seo_specialist', ARRAY['SEO','Google Analytics','Keyword Research','Backlinks','Content Marketing','On-Page SEO']),
('digital_marketing_specialist', ARRAY['Google Ads','Facebook Ads','SEO','Email Marketing','Analytics','Content Marketing']),
('salesforce_developer', ARRAY['Salesforce','Apex','Visualforce','Lightning','SOQL','Triggers']),
('sap_consultant', ARRAY['SAP','ABAP','FICO','MM','SD','HANA']),
('power_bi_developer', ARRAY['Power BI','DAX','SQL','Data Modeling','Excel','ETL']),
('tableau_developer', ARRAY['Tableau','SQL','Data Visualization','Calculations','Dashboards','Analytics']),
('linux_engineer', ARRAY['Linux','Shell Scripting','Networking','Bash','Python','Security']),
('ethical_hacker', ARRAY['Penetration Testing','Kali Linux','Metasploit','Wireshark','Python','Exploitation']),
('game_designer', ARRAY['Unity','C#','Blender','3D Modeling','Animation','UI/UX']),
('devops_consultant', ARRAY['Docker','Kubernetes','CI/CD','Terraform','AWS','Monitoring']),
('cloud_consultant', ARRAY['AWS','Azure','GCP','CloudFormation','Kubernetes','Docker']);
